apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: upload-route
spec:
  parentRefs:
    - name: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api/upload"
      backendRefs:
        - name: upload-svc
          namespace: services
          port: 8080
