apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: gateway
  labels:
    app: kong
spec:
  selector:
    matchLabels:
      app: kong
  replicas: 1
  template:
    metadata:
      name: kong-deployment
      namespace: gateway
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: rengumin/kong:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /usr/local/kong/declarative/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
---
apiVersion: v1
kind: Service
metadata:
  name: kong-svc-lb
  namespace: gateway
  labels:
    app: kong
spec:
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-ssl
      port: 8444
      targetPort: 8444
  type: LoadBalancer
