name: Trigger auto deployment for shopiew-be-ecom

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/shopiew-be-ecom-AutoDeployTrigger-b8a89483-647a-4d5b-88df-5ca43475ba26.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SHOPIEWBEECOM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SHOPIEWBEECOM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SHOPIEWBEECOM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.SHOPIEWBEECOM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHOPIEWBEECOM_REGISTRY_PASSWORD }}
          containerAppName: shopiew-be-ecom
          resourceGroup: shopiew-self
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


