// protoc --proto_path=/usr/local/include/:. --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative  proto/shop.proto
//export PATH="$PATH:$(go env GOPATH)/bin"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShopsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsByIDsRequest) Reset() {
	*x = GetShopsByIDsRequest{}
	mi := &file_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsByIDsRequest) ProtoMessage() {}

func (x *GetShopsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetShopsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

func (x *GetShopsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Define the response message
type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetShopsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	NotFoundIds   []string               `protobuf:"bytes,2,rep,name=not_found_ids,json=notFoundIds,proto3" json:"not_found_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsByIDsResponse) Reset() {
	*x = GetShopsByIDsResponse{}
	mi := &file_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsByIDsResponse) ProtoMessage() {}

func (x *GetShopsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetShopsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{2}
}

func (x *GetShopsByIDsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

func (x *GetShopsByIDsResponse) GetNotFoundIds() []string {
	if x != nil {
		return x.NotFoundIds
	}
	return nil
}

var File_shop_proto protoreflect.FileDescriptor

const file_shop_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shop.proto\x12\x05users\"(\n" +
	"\x14GetShopsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"*\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"^\n" +
	"\x15GetShopsByIDsResponse\x12!\n" +
	"\x05shops\x18\x01 \x03(\v2\v.users.ShopR\x05shops\x12\"\n" +
	"\rnot_found_ids\x18\x02 \x03(\tR\vnotFoundIds2Z\n" +
	"\fShopsService\x12J\n" +
	"\rGetShopsByIDs\x12\x1b.users.GetShopsByIDsRequest\x1a\x1c.users.GetShopsByIDsResponseB6Z4github.com/TranXuanPhong25/ecom/services/shops/protob\x06proto3"

var (
	file_shop_proto_rawDescOnce sync.Once
	file_shop_proto_rawDescData []byte
)

func file_shop_proto_rawDescGZIP() []byte {
	file_shop_proto_rawDescOnce.Do(func() {
		file_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)))
	})
	return file_shop_proto_rawDescData
}

var file_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shop_proto_goTypes = []any{
	(*GetShopsByIDsRequest)(nil),  // 0: users.GetShopsByIDsRequest
	(*Shop)(nil),                  // 1: users.Shop
	(*GetShopsByIDsResponse)(nil), // 2: users.GetShopsByIDsResponse
}
var file_shop_proto_depIdxs = []int32{
	1, // 0: users.GetShopsByIDsResponse.shops:type_name -> users.Shop
	0, // 1: users.ShopsService.GetShopsByIDs:input_type -> users.GetShopsByIDsRequest
	2, // 2: users.ShopsService.GetShopsByIDs:output_type -> users.GetShopsByIDsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shop_proto_init() }
func file_shop_proto_init() {
	if File_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_proto_goTypes,
		DependencyIndexes: file_shop_proto_depIdxs,
		MessageInfos:      file_shop_proto_msgTypes,
	}.Build()
	File_shop_proto = out.File
	file_shop_proto_goTypes = nil
	file_shop_proto_depIdxs = nil
}
